# Generated by Django 5.1.1 on 2024-10-14 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AberturaEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_primario', models.CharField(max_length=100)),
                ('nome_secundario', models.CharField(max_length=100)),
                ('nome_terciario', models.CharField(max_length=100)),
                ('atividade_principal', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('responsavel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
