# Generated by Django 5.1.1 on 2024-10-27 03:47

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidades', '0003_rename_abertura_contabilidade_data_abertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_etapa', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='InfoAdic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resp_tecnica', models.BooleanField(default=False)),
                ('nome_reponsavel', models.CharField(blank=True, max_length=80, null=True)),
                ('nmr_carteira_profissional', models.CharField(max_length=11)),
                ('uf', models.CharField(max_length=2)),
                ('area_resp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NomeProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_processo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='AberturaEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('opcoes_nomes_empresa', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('inscricao_imob', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('val_capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capital_integralizado', models.BooleanField(default=False)),
                ('data_integralizacao', models.DateField(blank=True, null=True)),
                ('area_empresa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empresa_anexa_resid', models.BooleanField(default=False)),
                ('endereco_apenas_contato', models.BooleanField(default=False)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidades.contabilidade')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societario.endereco')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societario.etapa')),
                ('info_adic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='societario.infoadic')),

                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societario.aberturaempresa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societario.etapa')),
                ('nome_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societario.nomeprocesso')),
                ('status_processo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessosEtapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societario.etapa')),
                ('nome_processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societario.nomeprocesso')),
            ],
        ),
    ]
