# Generated by Django 5.1.1 on 2024-10-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidades', '0003_rename_abertura_contabilidade_data_abertura'),
        ('societario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aberturaempresa',
            name='atividade_principal',
        ),
        migrations.RemoveField(
            model_name='aberturaempresa',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='aberturaempresa',
            name='contabilidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidades.contabilidade'),
        ),
        migrations.AddField(
            model_name='aberturaempresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aberturaempresa',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='aberturaempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aberturaempresa',
            name='nome_secundario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aberturaempresa',
            name='nome_terciario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aberturaempresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
