# Generated by Django 5.1.1 on 2024-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0002_socios'),
    ]

    operations = [
        migrations.AddField(
            model_name='aberturaempresa',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
