# Generated by Django 5.1.1 on 2024-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0003_aberturaempresa_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aberturaempresa',
            name='expire_at',
            field=models.DateTimeField(),
        ),
    ]
