# Generated by Django 5.1.1 on 2024-10-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0008_rename_etapaprocesso_etapaprocessos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etapas',
            new_name='Etapa',
        ),
        migrations.RenameModel(
            old_name='EtapaProcessos',
            new_name='EtapaProcesso',
        ),
        migrations.RenameModel(
            old_name='NomeProcessos',
            new_name='NomeProcesso',
        ),
        migrations.RenameModel(
            old_name='Processos',
            new_name='Processo',
        ),
    ]
