# Generated by Django 5.1.1 on 2024-10-24 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0009_rename_etapas_etapa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
