# Generated by Django 5.1.1 on 2024-10-24 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0010_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAdic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resp_tecnica', models.BooleanField(default=False)),
                ('nome_reponsavel', models.CharField(blank=True, max_length=80, null=True)),
                ('nmr_carteira_profissional', models.CharField(max_length=11)),
                ('uf', models.CharField(max_length=2)),
                ('area_resp', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='aberturaempresa',
            name='cep',
        ),
        migrations.AlterField(
            model_name='aberturaempresa',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='societario.endereco'),
        ),
    ]
