# Generated by Django 5.1.1 on 2024-11-30 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidades', '0003_rename_abertura_contabilidade_data_abertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('ordem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=37)),
            ],
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('expire_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidades.contabilidade')),
                ('etapa_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapa_atual', to='societario.etapas')),
                ('etapa_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapa_inicial', to='societario.etapas')),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='societario.tipoprocesso')),
            ],
        ),
    ]
