# Generated by Django 5.1.1 on 2024-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aberturaempresa',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
