# Generated by Django 5.1.1 on 2024-12-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidades', '0003_rename_abertura_contabilidade_data_abertura'),
        ('societario', '0002_remove_processos_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etapas',
            new_name='Etapa',
        ),
        migrations.RenameModel(
            old_name='Processos',
            new_name='Processo',
        ),
    ]
