# Generated by Django 5.1.1 on 2024-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0002_alter_aberturaempresa_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aberturaempresa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
