# Generated by Django 5.1.1 on 2024-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0003_alter_aberturaempresa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadic',
            name='area_resp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infoadic',
            name='nmr_carteira_profissional',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='infoadic',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
