# Generated by Django 5.1.1 on 2024-12-03 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0003_rename_etapas_etapa_rename_processos_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
                ('ordem', models.IntegerField()),
                ('obrigatoria', models.BooleanField(default=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapa', to='societario.etapa')),
            ],
        ),
    ]
