# Generated by Django 5.1.1 on 2024-11-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0004_alter_infoadic_area_resp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=80),
        ),
    ]
