# Generated by Django 5.1.1 on 2024-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0005_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
