# Generated by Django 5.1.1 on 2024-12-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0005_remove_processo_etapa_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='etapa_atual',
            new_name='etapa',
        ),
    ]
