# Generated by Django 5.1.1 on 2024-12-04 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0006_rename_etapa_atual_processo_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processo', to='societario.etapa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefa', to='societario.etapa'),
        ),
        migrations.CreateModel(
            name='StausTarefa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concluida', models.BooleanField(default=False)),
                ('sequencia', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapa', to='societario.etapa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stats_tarefa', to='societario.processo')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_tarefa', to='societario.tarefa')),
            ],
        ),
    ]
