# Generated by Django 5.1.1 on 2024-12-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0008_alter_processo_etapa_alter_staustarefa_tarefa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staustarefa',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_tarefa', to='societario.processo'),
        ),
    ]
