# Generated by Django 5.1.1 on 2024-12-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0009_alter_staustarefa_processo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StausTarefa',
            new_name='StatusTarefa',
        ),
    ]
