# Generated by Django 5.1.1 on 2024-12-19 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0011_endereco_infoadicionais_alter_processo_contabilidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormularioAbertura',
            new_name='FormularioAberturaEmpresa',
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=25)),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('separado', 'Separado judicialmente'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo')], max_length=10)),
                ('regime_casamento', models.CharField(blank=True, choices=[('separacao_total', 'Separação total de bens'), ('comunhao_parcial', 'Comunhão parcial de bens'), ('comunhao_universal', 'Comunhão universal de bens'), ('participacao_final', 'Participação final nos aquestos')], max_length=20, null=True)),
                ('profissao', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=14)),
                ('orgao_expedidor', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
                ('administrador', models.BooleanField(default=False)),
                ('tipo_administrador', models.CharField(choices=[('conjunto', 'Conjunto'), ('isoladamente', 'Isoladamente'), ('nao_aplica', 'Não se aplica')], max_length=15)),
                ('qtd_cotas', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='societario.formularioaberturaempresa')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='societario.endereco')),
            ],
        ),
    ]
