# Generated by Django 5.1.1 on 2024-12-19 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0012_rename_formularioabertura_formularioaberturaempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustarefa',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularioaberturaempresa',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='processo',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='administrador',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
