# Generated by Django 5.1.1 on 2024-12-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0013_statustarefa_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioaberturaempresa',
            old_name='info_adic',
            new_name='info_adicionais',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.CharField(max_length=60),
        ),
    ]
