# Generated by Django 5.1.1 on 2024-12-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0014_rename_info_adic_formularioaberturaempresa_info_adicionais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoadicionais',
            old_name='nome_reponsavel',
            new_name='nome_responsavel',
        ),
    ]
