# Generated by Django 5.1.1 on 2024-12-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0015_rename_nome_reponsavel_infoadicionais_nome_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioaberturaempresa',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
