# Generated by Django 5.1.1 on 2024-12-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0016_alter_formularioaberturaempresa_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='orgao_expedidor',
            field=models.CharField(max_length=10),
        ),
    ]
