# Generated by Django 5.1.1 on 2025-01-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0018_alter_socio_tipo_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioaberturaempresa',
            name='processo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_abertura', to='societario.processo'),
        ),
    ]
