# Generated by Django 5.1.1 on 2025-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0019_alter_formularioaberturaempresa_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustarefa',
            name='nao_aplicavel',
            field=models.BooleanField(default=False),
        ),
    ]
