# Generated by Django 5.1.1 on 2025-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0020_statustarefa_nao_aplicavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustarefa',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statustarefa',
            name='tipo_tributacao',
            field=models.CharField(blank=True, choices=[('SIMPLES', 'Simples Nacional'), ('LUCRO', 'Lucro Presumido'), ('REAL', 'Lucro Real')], max_length=10, null=True),
        ),
    ]
