# Generated by Django 5.1.1 on 2025-04-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0021_statustarefa_expire_at_statustarefa_tipo_tributacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustarefa',
            name='tipo_tributacao',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('lucro', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=10, null=True),
        ),
    ]
