# Generated by Django 5.1.1 on 2025-05-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0022_alter_statustarefa_tipo_tributacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioaberturaempresa',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='societario.endereco'),
        ),
        migrations.AlterField(
            model_name='formularioaberturaempresa',
            name='info_adicionais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='societario.infoadicionais'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='societario.endereco'),
        ),
        migrations.AlterField(
            model_name='statustarefa',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tarefa', to='societario.processo'),
        ),
    ]
