# Generated by Django 5.1.1 on 2025-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societario', '0023_alter_formularioaberturaempresa_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='observacao',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
